version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  thatchat: # name of the first service
    build: . # specify the directory of the Dockerfile
    ports:
      - "3000:3000" # specify port forwarding

  thatchat-server: #name of the second service
    build: ..\thatchat-server # specify the directory of the Dockerfile
    links:
      - "db:database"
    ports:
      - "5000:5000" #specify ports forwarding

  db: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forwarding






#https://scotch.io/tutorials/create-a-mean-app-with-angular-2-and-docker-compose